require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Remove Flipper configuration
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RN_HealthKit' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Remove Flipper configuration
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add react-native-health pod
  pod 'RNAppleHealthKit', :path => '../node_modules/react-native-health'
  
  # Add SQLite storage pod
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Set deployment target and C++ settings
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        
        # Add C++ standard library settings
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = [
          '$(OTHER_CFLAGS)',
          '-DFOLLY_NO_CONFIG',
          '-DFOLLY_MOBILE=1',
          '-DFOLLY_USE_LIBCPP=1',
          '-DFOLLY_CFG_NO_COROUTINES=1',
          '-DFOLLY_HAVE_CLOCK_GETTIME=1'
        ]
      end
    end

    # Enable HealthKit capabilities
    installer.pods_project.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_HEALTHKIT=1'
      config.build_settings['OTHER_LDFLAGS'] ||= ['$(inherited)']
      config.build_settings['OTHER_LDFLAGS'] << '-framework' << 'HealthKit'
    end
  end
end
